# Generated by Django 2.1.7 on 2019-03-01 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_name', models.CharField(max_length=50)),
                ('major_ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visColPath.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visColPath.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='visColPath.Student')),
            ],
        ),
    ]
