# Generated by Django 2.1.7 on 2019-03-09 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visColPath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date Generated')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='course',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_ID',
            new_name='netID',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
