# Generated by Django 2.1.7 on 2019-03-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visColPath', '0002_auto_20190309_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pathway',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
