# Generated by Django 2.1.7 on 2019-03-09 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visColPath', '0003_auto_20190309_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date Generated')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('major', models.CharField(max_length=50)),
                ('netID', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visColPath.Student'),
        ),
    ]
